root: true
env:
  browser: true
  node: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: 'babel-eslint'
extends:
  # https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
  # consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
  - plugin:vue/recommended
plugins:
  - vue # required to lint *.vue files
  - node
# // add your custom rules here
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
